// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2V4AoUf4o-yb9FYwk0Ad1rhNniQqLK1w',
    appId: '1:329978158119:web:87208bac6256111f40c202',
    messagingSenderId: '329978158119',
    projectId: 'shopping-361e0',
    authDomain: 'shopping-361e0.firebaseapp.com',
    storageBucket: 'shopping-361e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu0B4jGx9NepJB0_1prNqg-Hb8eLabNPc',
    appId: '1:329978158119:android:82c0eba55108766140c202',
    messagingSenderId: '329978158119',
    projectId: 'shopping-361e0',
    storageBucket: 'shopping-361e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBarkqQI_pyybUzOTxYggAgrEaTt65Yjs',
    appId: '1:329978158119:ios:2d26a45b978b5e2440c202',
    messagingSenderId: '329978158119',
    projectId: 'shopping-361e0',
    storageBucket: 'shopping-361e0.appspot.com',
    androidClientId: '329978158119-oubus5r2kjo8f51ctr7e82fucbnh73qu.apps.googleusercontent.com',
    iosClientId: '329978158119-12hrqgvmjp7jkr49vi4219g6a2fbpm6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.shop',
  );
}
